Range query
pisa-engine/pisa pull request #108
Opened 2019-02-17 23:21 UTC by amallia

Heavily based on previous work from @elshize from https://github.com/pisa-engine/pisa/pull/102

2019-02-18 07:16 UTC, amallia commented
@elshize please review. It is just a first step, but it includes interesting changes. 
I have verified performance and correctness. 

After merging it, I will continue cleaning up the algorithms doing something similar to what you have done. I still prefer to address it in a separate PR.

2019-02-19 16:12 UTC, elshize commented
Why exactly do you want to do this in many PR's? This means more testing for efficiency, more code reviews, and more coding. We're just doing what we've already done. This is a lot of code, going through it again and again and again is not only annoying, but also wasteful.

Didn't you say you already got good performance? After all that work you did, do you really wanna scratch that and do it over?

2019-02-22 17:01 UTC, elshize requested changes

2019-02-22 17:01 UTC, elshize commented on include/pisa/cursor/block_max_scored_cursor.hpp
> +    enum_type  docs_enum;
How about adding `next()`, `next_geq()`, `docid()` and `freq()` that will call `docs_enum.next()`, etc? If you add `always_inline`, then you're surely getting the same level of indirection as now, only with better encapsulation and a unified interface across all cursors (remember that a non-scored cursor is called directly whereas scored indirectly, yet both are called `cursor`, which suggests similar behavior).

The same goes for `score()`, just make a member function that will do `ordered_cursors[i]->w.score() * ordered_cursors[i]->q_weight` behind the scenes. The only differences are in where this piece of code and how clear it is from the point of the algorithm. Also, less code repetition, fewer bugs.

2019-02-22 17:01 UTC, elshize commented on include/pisa/cursor/block_max_scored_cursor.hpp
> +    typedef typename Index::document_enumerator     enum_type;
We should use `using enum_type = ` syntax in any new code:
1. It's more intuitive, works as any other thing in the language, i.e., whatever you define is on the left.
2. It's more generic, literally. It works with templates, so whenever we need templated typedefs, we have to use it, which introduces unnecessary inconsistencies with other `typedef`s.

2019-02-22 17:01 UTC, elshize commented on include/pisa/cursor/block_max_scored_cursor.hpp
> +template <typename Index, typename WandType, typename scorer_type = bm25>
Defining `scorer_type = bm25` as the last param is a bit problematic. Here's why:

Let's say you want to construct `bm25` cursors, you type this:
```cpp
make_block_max_scored_cursors(index, wdata, terms);
```
Swell. Now, with a non-default scorer:
```cpp
make_block_max_scored_cursors<Index, Wand, QLikelihood>(index, wdata, terms);
```
You need to define all types, which means you might as well just use the constructor and define everything explicitly.

I see two possible designs:

1. No default scorer: because why would BM25 be more default than anything else? Then you can simply move the type param to the front and always get cursors this way:
```cpp
make_block_max_scored_cursors<bm25>(index, wdata, terms);
```
2. You use scorer "tags". (Note that this can be used with or without defaults.)
```cpp
struct BM25_Tag {
    auto operator()(auto index, auto term, auto term_weight) { /* impl */ };
} bm25;
```
I used `auto` instead of templates to be more concise, you get the idea. Then, the signature would be:
```cpp
template <typename Index, typename WandType, typename ScorerTag>
[[nodiscard]] auto make_block_max_scored_cursors(Index const &index, WandType const &wdata,
                                                 term_id_vec terms, ScorerTag tag) {
    ...
    auto score_function = tag(index, term, term_weight);
    ...
}
```
And then you call it like this:
```cpp
make_block_max_scored_cursors(index, wdata, terms, bm25);
```
Awesome!

2019-02-22 17:01 UTC, elshize commented on include/pisa/cursor/cursor.hpp
> +    typedef typename Index::document_enumerator cursor;
`using`

2019-02-22 17:01 UTC, elshize commented on include/pisa/cursor/block_max_scored_cursor.hpp
> +    for (auto term : query_term_freqs) {
This looks like a perfect place to use ranges:
```cpp
auto cursors = ranges::view::transform(query_terms_freqs, [](auto &&term) {
    ...
    return cursor_type{...};
}) | ranges::to_vector;
```

2019-02-22 17:01 UTC, elshize commented on include/pisa/cursor/cursor.hpp
> +    cursors.reserve(query_term_freqs.size());
This place is even better for ranges.

2019-02-22 17:01 UTC, elshize commented on include/pisa/cursor/max_scored_cursor.hpp
> +template <typename Index, typename Scorer>
See all comments about `block_max_scored_cursor`

2019-02-22 17:01 UTC, elshize commented on include/pisa/cursor/scored_cursor.hpp
> +struct scored_cursor {
See all comments about `block_max_scored_cursor`.

2019-02-22 17:01 UTC, elshize commented on include/pisa/query/algorithm/and_query.hpp
>                  if (with_freqs) {
`if constexpr (with_freqs)`

2019-02-22 17:01 UTC, elshize commented on include/pisa/query/algorithm/and_query.hpp
> +    uint64_t operator()(std::vector<Cursor> &&cursors) const {
So if we use `&&` on a collection, we could as well do:
```cpp
template<typename CursorRange>
uint64_t operator()(CursorRange &&cursors) const
{
    using cursor_type = CursorRange::value_type;
    ...
}
```

2019-02-22 17:01 UTC, elshize commented on include/pisa/query/algorithm/or_query.hpp
>                      if (with_freqs) {
`if constexpr`

2019-02-22 17:01 UTC, elshize commented on include/pisa/query/algorithm/ranked_or_taat_query.hpp
> +        for(auto&& cursor : cursors) {
Format the entire loop.

2019-02-22 17:01 UTC, elshize commented on include/pisa/query/algorithm/wand_query.hpp
>                      ;
A hanging semicolon like that is giving me a heart attack. Just `for (...) {}`

2019-02-22 17:01 UTC, elshize commented on src/profile_queries.cpp
> +                remove_duplicate_terms(terms);
Won't `make_cursors` already remove duplicate terms?

2019-02-22 17:01 UTC, elshize commented on test/test_ranked_queries.cpp
> +        typedef single_index IndexType;
`using`

2019-02-22 18:40 UTC, amallia commented on include/pisa/cursor/block_max_scored_cursor.hpp
> +    enum_type  docs_enum;
I will address this in the next PR. I am taking a note.

2019-02-22 18:41 UTC, amallia commented on include/pisa/cursor/block_max_scored_cursor.hpp
> +template <typename Index, typename WandType, typename scorer_type = bm25>
It will be done once we introduce other scorers

2019-02-22 19:40 UTC, elshize approved these changes
Looks good.

2019-02-22 20:06 UTC, merged