Extracting query times
pisa-engine/pisa pull request #138
Opened 2019-03-08 02:18 UTC by elshize

2019-03-08 02:21 UTC, elshize commented
In progress. Still want to: (a) add an option to suppress logging (`--silent`? any other suggestion?), and (b) write logs to stderr by default (now it's written to stdout).

2019-03-08 18:07 UTC, elshize commented
@amallia Ready for review.

2019-03-28 16:32 UTC, amallia requested changes

2019-03-28 16:32 UTC, amallia commented on src/queries.cpp
> +    app.add_flag("--extract", extract, "Extract individual query times")->needs(terms_opt);
I dont think `extract` needs `terms_opt `

2019-03-28 16:32 UTC, amallia requested changes

2019-03-28 16:32 UTC, amallia commented on docs/source/query_index.md
> +      --extract Needs: --terms    Extract individual query times
Same here

2019-03-28 16:33 UTC, amallia commented
Everything looks good, a part a small think related to CLI.
After fixing this we can merge it!

2019-03-29 15:55 UTC, amallia approved these changes

2019-03-29 16:10 UTC, merged