BMA
pisa-engine/pisa pull request #167
Opened 2019-04-15 09:43 UTC by amallia

2019-04-15 10:25 UTC, elshize requested changes

2019-04-15 10:25 UTC, elshize commented on include/pisa/query/algorithm/block_max_ranked_and_query.hpp
> +    typedef bm25 scorer_type;
`using scorer_type = bm25`

2019-04-15 10:25 UTC, elshize commented on include/pisa/query/algorithm/block_max_ranked_and_query.hpp
> +        if (cursors.empty())
Parens around `break`

2019-04-15 10:25 UTC, elshize commented on include/pisa/query/algorithm/block_max_ranked_and_query.hpp
> +                for (size_t j = 1; j < ordered_cursors.size(); ++j) {
What's a `j`?

2019-04-23 03:07 UTC, JMMackenzie commented
Just committed some new attempts at this. It still doesn't quite work properly as far as I can tell (it can occasionally miss a document that should be scored). However, it generally seems closer to working than before. Will revisit soon.

2019-05-06 07:09 UTC, closed without merging