Pass top-k queue to the query algorithm
pisa-engine/pisa pull request #288
Opened 2019-11-25 20:44 UTC by amallia

2019-12-20 07:10 UTC, amallia commented
@elshize while I fix this, could you give it a look in the meantime?

2019-12-21 14:41 UTC, elshize requested changes
Looks good other than the one comment.

2019-12-21 14:41 UTC, elshize commented on include/pisa/query/algorithm/range_taat_query.hpp
> +        process_range(cursors, max_docid, accumulator);
I think we'll end up processing twice the last range if the total length is a multiplier of the range size. I think the `for` condition should be instead `end + range_size < max_docid`, and that should fix it.

2019-12-22 13:07 UTC, elshize commented
Looks good, what's the problem with Travis, is it timing out?

2019-12-23 17:35 UTC, closed without merging